bansalpravesh1/DSACodes

- Java/arraylistAdd.java
Added a code for java arraylist basics
> arraylist intro

- CPP/TrickyPermutations.cpp
Will print non-repetitive permutations of a particular string in Lexicographic order.
> Add TrickyPermutations

- CPP/ReplaceAllPi.cpp
Will replace "Pi" with 3.14 using recursion.
> Add ReplaceAllPi.cpp

- Java/Sorting Algorithms-JAVA/BubbleSort.java
- Java/Sorting Algorithms-JAVA/InsertionSort.java
- Java/Sorting Algorithms-JAVA/MergeSort.java
- Java/Sorting Algorithms-JAVA/QuickSort.java
- Java/Sorting Algorithms-JAVA/SelectionSort.java
I have added the following Sorting Algorithms in JAVA:
- Bubble Sort
- Insertion Sort
- Quick Sort
- Merge Sort
- Selection Sort
> Added Sorting Algorithms in Java

- Java/CommandLine.java
This program made to Print Command Line Arguments.
> Print Command Line Arguments

- Java/bouncy_num.java
> Added a Java Code

- Java/Student.java
Please review my PR. I have added sample class  and object example in JAVA.
> Sample class file added in JAVA

- Python/Boyre Moore Voting Algorithm.py
Hi 👋🏻,
It's my first time participating in open source contributions. If my PR has any mistake, please guide me ✌.
**_Added Boyre Moore Voting Algorithm_**
Used to find majority elements in an array.
> Added Boyre Moore Voting Algorithm

- Android Apps/Calculator/.project
- Android Apps/Calculator/.settings/org.eclipse.buildship.core.prefs
contributing in hacktoberfest2021 
Added counting sort algorithm in java.
Please accept or add label hacktoberfest-accepted
Thankyou!!
> count sort java

- Python/Merging Overlapping Intervals.py
Hi 👋🏻,
It's my first time participating in open source contributions. If my PR has any mistake, please guide me ✌.
**_Added Merge Overlapping Intervals_**
Algorithm to find the overlapping intervals in an 2D array with the a lower time complexity than the solutions on the internet.
> Added Merge Overlapping Intervals.py

- Python/Setting Matrix Values 0.py
Hi 👋🏻,
This PR **_Added Set Matrix Values Algorithm Refined to O(n^2)_** in the **_~Python/_**
Used an approach whilch traverses the 2D array in a refined approach as to prevent extra space complexity.
If my PR has any mistake, please guide me ✌.
> Added Set Matrix Values Algorithm Refined to O(n^2)

- CPP/Caeser Cipher Algorithm.cpp
Added a classic **_ROT13 Cryptographic Cipher i.e. Caeser Cipher_**, fully explained and commented, in Python Folder and to provide value to the seekers of this repository.
**_Included explanation_** of Ciphering and Deciphering this Cipher.
> Added a ROT13 Cryptographic Cipher i.e. Caeser Cipher with Encrypt and Decrypt Source Code

- Python/Sorting Duplicates Containing N-1.py
Hi 👋🏻,
This PR **_Added Sorting Duplicates Algorithm's Edge Case i.e N-1 Elements_** in the **_~Python/_**
And edge case problem to find duplicates in array whose elements ranges from 1 to N. Used an approach whilch traverses the array and finds the duplicates in O(n).
If my PR has any mistake, please guide me ✌.
> Added Sorting Duplicates Algorithm's Edge Case i.e N-1 Elements

- Python/Sliding Window Algorithms.py
Added two variants of **_Sliding Window Algorithm_**, fully explained and commented, in Python Folder to provide value to the seekers of this repository.
**_Variant 1:_** Maximum/Minimum Sum of K size subarray with time Complexity of O(n).
**_Variant 2:_** Smallest subarray with given Sum with time Complexity of O(n²).
> Added Sliding Window Algorithms (2 variants) in Python Algorithms

- BinarySearch.java
- Java/ContainsDuplicate.java
- Java/FindAllDuplicates.java
- Java/FirstMissingPositive.java
- Java/kthLargestElement.java
- Java/missingNumber.java
I would love to contribute Leetcode good question
> Added binary search code.

- CPP/ElementThatAppearsonce.cpp
The following program finds the element that appears only once from the sorted array.
> element that appears once program added

- Java/Container with most water.java
Java solution to 'Container with most water' problem
> Create Container with most water.java

- CPP/kadanes algorithm
This is the code for kadanes algorithm in c++
> kadanes algorithm

- Java/Pascal's triangle.java
Java code to generate Pascal's Triangle
> Create Pascal's triangle.java

- CPP/linked-list.cpp
Implemented the linked list data structure in C++.
> Implemented linked list in C++

- Java/BoyerMoorVoting.java
- Java/VPSWAR.java
**1. Variable Precision SWAR algorithm**
To count the number of bits set in a given number can be done via a SWAR (SIMD Within A Register) algorithm. The performance of this algorithm is very good (16 instructions when compiled with gcc -O3).
```
i = (i & 0x55555555) + ((i>>1) & 0x55555555)
i = (i & 0x33333333) + ((i>>2) & 0x33333333)
i = (i & 0x0F0F0F0F) + ((i>>4) & 0x0F0F0F0F)
i = (i * 0x01010101) >> 24
return i
``` 
**2. Boyer Moor Voting algorithm**
The Boyer–Moore majority vote algorithm is an algorithm for finding the majority of a sequence of elements using linear time and constant space.
```
Initialize an element m and a counter i with i = 0
For each element x of the input sequence:
If i = 0, then assign m = x and i = 1
else if m = x, then assign i = i + 1
else assign i = i − 1 …
```
> Added two algorithms in java - VPSWAR, Boyer Moor Voting

- CPP/LinkedList_AppendNode.cpp
Add a node in a Linked List CPP
> Add a node in a Linked List CPP

- Java/Zebra_Jump
- Python/avl tree
AVl Tree implementation in python
> AVL Tree Py

- Java/maximumSubarraySum.java
Added Java code for Maximum contiguous subarray sum (Kadane's Algorithm) problem
> Added maximum contiguous subarray sum (Kadane's Algorithm)

- Python/depth_first_search.py
Added code for Depth-first search using Python.
> DFS algo in python

- Python/breadth_first_search.py
Added code for Breadth-First Search using python
> BFS algo in python

- CPP/maximum-pairwise-product.cpp
Contains both regular and fast implementations. Refer [this](https://stackoverflow.com/questions/47365771/maximum-pairwise-product-fast-solution) for more information.
> Added Maximum Pairwise Product solution
